poster : poster.tex references.bib
	pdflatex poster.tex
	bibtex poster.aux
	pdflatex poster.tex
	pdflatex poster.tex

clean :
	rm poster.aux poster.bbl poster.blg poster-blx.bib poster.log poster.nav poster.out poster.run.xml poster.snm poster.toc

