leaf : main.cpp Headers/ConfigFile.hpp Headers/ConfigFile.tpp Headers/Convert.hpp Headers/Corrupter.hpp Headers/Corrupter.tpp Headers/Dim.hpp Headers/Dim.tpp Headers/Errors.hpp Headers/Errors.tpp Headers/fast_updates.hpp Headers/full_statistics.hpp Headers/init.hpp Headers/Interpolator.hpp Headers/LapackFunctions.hpp Headers/RVM.hpp Headers/SignalBasis.hpp Headers/SignalBasis.tpp Headers/Signal.hpp Headers/SignalSettings.hpp Headers/SignalSettings.tpp Headers/Signal.tpp Headers/Timer.hpp Headers/utilities.hpp
	g++-5.3 main.cpp -o leaf -std=c++11 -llapack -lblas -O3 # -Wall -Wextra -pedantic

clean :
	rm leaf