leaf : main.cpp ConfigFile.hpp ConfigFile.tpp Convert.hpp Corrupter.hpp Corrupter.tpp Dim.hpp Dim.tpp Errors.hpp Errors.tpp fast_updates.hpp full_statistics.hpp init.hpp Interpolator.hpp LapackFunctions.hpp RVM.hpp SignalBasis.hpp SignalBasis.tpp Signal.hpp SignalSettings.hpp SignalSettings.tpp Signal.tpp Timer.hpp utilities.hpp
	g++ main.cpp -o leaf -llapack -lblas -O3

clean :
	rm leaf